import Foundation
let s = WechatSession()
assert(s.begin("one", state: "secure-state") == nil)
assert(s.begin("two") == "busy")
assert(s.consumeAuthorization("forged") == nil)
assert(s.consumeAuthorization(nil) == nil)
assert(s.submitted("one", accepted: true))
assert(s.consumeAuthorization("secure-state") == "one")
assert(s.consumeAuthorization("secure-state") == nil)
assert(s.begin("one") == "invalid_content")
assert(s.begin("two", state: "next-state") == nil)
assert(!s.cancel("one"))
assert(s.cancel("two"))
assert(s.begin("three", state: "third-state") == nil)
assert(!s.submitted("two", accepted: false))
assert(s.consumeAuthorization("next-state") == nil)
assert(s.consumeAuthorization("third-state") == "three")
print("Swift OAuth state, concurrency, duplicate and late callback checks passed")
