[versions]
agp = "8.10.1"
kotlin = "2.2.21-1.0.0"
kuikly = "2.28.0-2.0.21-ohos"

[libraries]
kuikly-core = { module = "com.tencent.kuikly-open:core", version.ref = "kuikly" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
